# Generated by Django 4.1.3 on 2022-11-29 19:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_appuser_options_alter_appuser_managers_and_more'),
        ('heros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='heros.hero')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratingHeros', to='users.appuser')),
            ],
        ),
    ]
